name: Run Python Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Run Python files
        run: |
          # Find all Python files in the repository
          for file in $(find . -name '*.py'); do
            if [ -f "$file" ]; then
              echo "Running $file"
              # Provide default inputs for scripts that require input
              case "$file" in
                *"Opdracht-1.py")
                  echo "Thomas" | python "$file"
                  ;;
                *"Opdracht-4.py")
                  echo -e "python123" | python "$file"
                  ;;
                *)
                  python "$file"
                  ;;
              esac
            else
              echo "$file does not exist."
            fi
          done