name: Run Python Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Python files
        run: |
          # Vind alle Python-bestanden in de repository
          for file in $(find . -name '*.py'); do
            if [ -f "$file" ]; then
              echo "Running $file"
              # Voorzie invoer voor specifieke scripts
              case "$file" in
                *"Opdracht-1.py")
                  echo "Thomas" | python "$file"
                  ;;
                *"Opdracht-4.py")
                  echo -e "python123" | python "$file"
                  ;;
                *"steenpapierschaar.py")
                  # Test steen-papier-schaar script met alle keuzes en afsluiten met 'nee'
                  echo -e "steen\nnee" | python "$file"
                  echo -e "papier\nnee" | python "$file"
                  echo -e "schaar\nnee" | python "$file"
                  ;;
                *)
                  python "$file"
                  ;;
              esac
            else
              echo "$file does not exist."
            fi
          done
